Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04-arm64"
  config.vm.hostname = "pl-000"

  config.vm.provider "parallels" do |p|
    p.memory = 2048
    p.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"
end

